### ISSUE TITLE
Add 'back to top' button

### ISSUE THREAD

**Issue by melanieseltzer** [melanieseltzer/es6-all-the-things#6]
Since the page is quite long, I feel like a 'back to top' button would be useful.

**Comment by bbenefield89** [comment]
Hey, @melanieseltzer is this up for grabs? Wouldn't mind jumping on this. If so, did you have a design in mind? Maybe something as simple as an arrow with a circular background from font-awesome and could just use the same color scheme as the hero section (gradient background, white color)?

**Comment by melanieseltzer** [comment]
It's all yours! Sounds good, I thought something along those lines 😄

**Comment by bbenefield89** [comment]
Awesome :tada:. Just to make sure, should I run the `build` script before submitting a PR?

**Comment by melanieseltzer** [comment]
No need since build isn't on master, you can just work in src. Once you're done I'll merge your changes then run the deploy script which does the build automatically. Thanks for working on this 😄

**Comment by melanieseltzer** [comment]
@bbenefield89 Just merged in #2 (sticky menu) which may affect your work. Make sure to rebase :)
